hosts = {
  "ansible-controller" => '99',
  "web-1" => '11',
  "web-2" => '12',
  "web-3" => '13',
  "balancer" => '80'
}

Vagrant.configure("2") do |config|
  hosts.each do |name, octet|
    config.vm.define name do |machine|
      machine.vm.hostname = "%s" % name
      machine.vm.network :private_network, ip: '192.168.33.'+octet
	  machine.vm.network "forwarded_port", guest: '22', host: '22'+octet, id: "ssh"
	  machine.vm.network "forwarded_port", guest: '80', host: '80'+octet, id: "web"
      machine.vm.provider "virtualbox" do |v|
          v.name = name
          v.memory = "256"
		  v.cpus = "1"
      end
	  if name == 'ansible-controller'
	    machine.vm.provision "shell", inline: "apt install -y ansible sshpass"
	  end
    end
  end
  config.vm.box = "debian_box"
  config.ssh.username = 'root'
  config.ssh.password = 'root'
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
end